<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Remove</name>
   <tag></tag>
   <elementGuidId>4e9db624-89ac-4162-940b-d09f98a7d8f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._42ft._5upp._50zy.layerCancel._36gl._50-0._50z_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48f8971a-ddb4-41b7-9cdb-b9564ad87fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _5upp _50zy layerCancel _36gl _50-0 _50z_</value>
      <webElementGuid>4ba68700-0298-4239-86f0-34534efd49fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98ad32f1-bdac-493a-aa36-8398331fc795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>cb65c4bf-cc8b-48bd-86b2-43e622aabf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ad13300d-e0b8-4f68-a598-fe2956afaea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>974432d9-0e7f-4623-aadd-62fe2ceed828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_l&quot;)/div[@class=&quot;_53ij&quot;]/div[@class=&quot;_53iv&quot;]/div[@class=&quot;_21es&quot;]/button[@class=&quot;_42ft _5upp _50zy layerCancel _36gl _50-0 _50z_&quot;]</value>
      <webElementGuid>170c1fce-3c26-4c1e-b987-dfbaa313335c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>4030057a-09a3-410d-a085-25beb0c6c4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js_l']/div/div/div/button</value>
      <webElementGuid>79c681ee-87de-461a-87d7-e470446169cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Altering'])[1]/following::button[1]</value>
      <webElementGuid>b628d425-bf2d-4a38-8490-76fb8a7c4b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click your picture or add an account.'])[1]/following::button[1]</value>
      <webElementGuid>27d9f9e7-995e-445a-92aa-6cefc1cdd3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next time you log in, click your picture. To remove an account from this page, click here.'])[1]/preceding::button[1]</value>
      <webElementGuid>4772f2c3-5bfc-4505-8423-9b83608bcf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Account'])[1]/preceding::button[1]</value>
      <webElementGuid>b3710ae0-fe3d-4d28-92a7-affbd8e3567f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>257a2a9b-1c3f-4771-b2bc-2acdb611122b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6eb37526-4fa8-4475-8f59-14b6df24ad33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Remove' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>dd58c71e-7acd-4ddb-aea4-6df29b57dcae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
